# Estas são as opções de patrocínio e suporte para o projeto OpenCEP Ultra

# Substitua os campos abaixo pelos seus links reais
github: [kedllon] # Substitua pelo seu nome de usuário oficial do GitHub
custom: ["https://www.buymeacoffee.com/seu-usuario", "https://paypal.me/seu-usuario", "Chave PIX: seu-email-ou-cpf-aqui"]
